---
cisco_only:
  hosts:
    rtr1:
      ansible_host: 3.15.71.20 
    rtr2:
      ansible_host: 3.21.249.77
    rtr3:
      ansible_host: 3.130.133.107
    rtr4:
      ansible_host: 3.134.226.219
  vars:
   ansible_connection: ansible.netcommon.network_cli
   ansible_network_os: cisco.ios.ios

  